// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // TODO: Replace with your Web Firebase config
      // You can get this from the Firebase Console -> Project Settings -> General -> Your apps -> Web
      throw UnsupportedError(
        'Web Firebase configuration not found. Please configure your web app in Firebase Console and add details here.',
      );
      /*
      return const FirebaseOptions(
        apiKey: 'AIzaSyCZEfxw8-WQzqzXskWRYct3bEUWQmZkUZg', // Example: Use same as Android if unrestricted, or create new
        appId: 'YOUR_WEB_APP_ID',
        messagingSenderId: '589102136702',
        projectId: 'kigali-city-navigator',
        authDomain: 'kigali-city-navigator.firebaseapp.com',
        storageBucket: 'kigali-city-navigator.firebasestorage.app',
      );
      */
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZEfxw8-WQzqzXskWRYct3bEUWQmZkUZg',
    appId: '1:589102136702:android:a7ea73dfb05916ab12072f',
    messagingSenderId: '589102136702',
    projectId: 'kigali-city-navigator',
    storageBucket: 'kigali-city-navigator.firebasestorage.app',
  );
}
